import { describe, it, expect } from 'vitest'
import { extractYaml, normalizeEncodedInput } from '../src/extract'

describe('extractYaml', () => {
  it('returns pure YAML as-is', () => {
    const yaml = 'services:\n  app:\n    image: nginx\n'
    const result = extractYaml(yaml)
    expect(result.yaml).toBe(yaml.trim())
    expect(result.error).toBeNull()
  })

  it('strips leading shell command', () => {
    const input = '$ sudo docker compose config\nservices:\n  app:\n    image: nginx\n'
    const result = extractYaml(input)
    expect(result.yaml).toContain('services:')
    expect(result.yaml).not.toContain('$ sudo')
    expect(result.error).toBeNull()
  })

  it('strips leading blank lines', () => {
    const input = '\n\n\n  \nservices:\n  app:\n    image: nginx\n'
    const result = extractYaml(input)
    expect(result.yaml).toContain('services:')
    expect(result.error).toBeNull()
  })

  it('strips trailing terminal prompt', () => {
    const input = 'services:\n  app:\n    image: nginx\nuser@host:~$ '
    const result = extractYaml(input)
    expect(result.yaml).toContain('services:')
    expect(result.yaml).not.toContain('user@host')
    expect(result.error).toBeNull()
  })

  it('returns error for pure garbage text', () => {
    const result = extractYaml('this is just some random text with no yaml')
    expect(result.error).toBeTruthy()
    expect(result.yaml).toBeNull()
  })

  it('returns error for empty input', () => {
    const result = extractYaml('')
    expect(result.error).toBeTruthy()
    expect(result.yaml).toBeNull()
  })

  it('returns error for whitespace-only input', () => {
    const result = extractYaml('   \n  \n  ')
    expect(result.error).toBeTruthy()
    expect(result.yaml).toBeNull()
  })

  it('handles docker run command before YAML', () => {
    const input = '$ docker run --rm ghcr.io/red5d/docker-autocompose sonarr\nservices:\n  sonarr:\n    image: linuxserver/sonarr\n'
    const result = extractYaml(input)
    expect(result.yaml).toContain('services:')
    expect(result.yaml).not.toContain('docker run')
    expect(result.error).toBeNull()
  })

  it('handles comment lines before YAML', () => {
    const input = '# Generated by docker-autocompose\nservices:\n  app:\n    image: nginx\n'
    const result = extractYaml(input)
    expect(result.yaml).toContain('services:')
    expect(result.error).toBeNull()
  })

  it('suggests copy issue for truncated YAML', () => {
    const input = 'services:\n  app:\n    image: nginx\n    environment:\n      - FOO='
    const result = extractYaml(input)
    // Should still try to parse — truncated YAML may or may not be valid
    // The key is we don't crash
    expect(result.error === null || typeof result.error === 'string').toBe(true)
  })

  it('handles version key at start', () => {
    const input = 'version: "3.6"\nservices:\n  app:\n    image: nginx\n'
    const result = extractYaml(input)
    expect(result.yaml).toContain('services:')
    expect(result.error).toBeNull()
  })

  it('handles name key at start (docker compose config style)', () => {
    const input = 'name: myproject\nservices:\n  app:\n    image: nginx\n'
    const result = extractYaml(input)
    expect(result.yaml).toContain('services:')
    expect(result.error).toBeNull()
  })

  it('decodes common HTML entities in pasted input', () => {
    const input =
      'services:\n  app:\n    image: nginx\n    environment:\n      - FOO=&quot;bar&quot;\n      - BAZ=a&amp;b\n'
    const result = extractYaml(input)
    expect(result.error).toBeNull()
    expect(result.yaml).toContain('FOO="bar"')
    expect(result.yaml).toContain('BAZ=a&b')
  })

  it('decodes percent-encoded paths in pasted input', () => {
    const input =
      'services:\n  app:\n    image: nginx\n    volumes:\n      - /mnt/My%20Files:/data\n      - /opt/foo%2Fbar:/x\n'
    const result = extractYaml(input)
    expect(result.error).toBeNull()
    expect(result.yaml).toContain('/mnt/My Files:/data')
    expect(result.yaml).toContain('/opt/foo/bar:/x')
  })

  it('leaves a single literal % alone (not a misread encoding)', () => {
    const input = 'services:\n  app:\n    image: nginx\n    environment:\n      - GREET=hi 100% done\n'
    const result = extractYaml(input)
    expect(result.error).toBeNull()
    expect(result.yaml).toContain('100% done')
  })
})

describe('normalizeEncodedInput', () => {
  it('passes plain text through unchanged', () => {
    expect(normalizeEncodedInput('plain text')).toBe('plain text')
  })

  it('decodes named HTML entities', () => {
    expect(normalizeEncodedInput('a &amp; b &lt; c')).toBe('a & b < c')
  })

  it('decodes numeric HTML entities', () => {
    expect(normalizeEncodedInput('&#34;quote&#34;')).toBe('"quote"')
  })

  it('decodes hex HTML entities', () => {
    expect(normalizeEncodedInput('&#x22;quote&#x22;')).toBe('"quote"')
  })

  it('decodes multiple percent sequences together', () => {
    expect(normalizeEncodedInput('/path/with%20spaces/and%2Fslashes')).toBe('/path/with spaces/and/slashes')
  })

  it('leaves a lone % sign alone', () => {
    // Only one %-sequence and the test is conservative — keep literal.
    expect(normalizeEncodedInput('battery 100% full')).toBe('battery 100% full')
  })

  it('handles malformed percent sequences gracefully', () => {
    // %ZZ is not valid hex; should be left as-is rather than throwing.
    expect(() => normalizeEncodedInput('value with %ZZ and %20 here %2F')).not.toThrow()
  })

  it('handles mixed HTML and percent encoding', () => {
    expect(normalizeEncodedInput('foo &amp; /a%20b')).toBe('foo & /a%20b') // percent stays — only one %20
    expect(normalizeEncodedInput('foo &amp; /a%20b/c%20d')).toBe('foo & /a b/c d') // two %20 → decoded
  })
})
